[features]
seeds = false
skip-lint = false
[programs.devnet]
tut1 = "9tQ16Efw5TgKEYnx5qPxULB7kBBsA5jzRKQBNmP3h2bi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vhits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
